apiVersion: v1
kind: ConfigMap
metadata:
  name: interview-api-config
  namespace: default
data:
  LOG_LEVEL: "INFO"
  MAX_WORKERS: "2"
  FEATURE_FLAGS: "enable_cache=false"
  API_KEY: "supersecret123"
